### ISSUE TITLE
Number result and not boolean (true & false) when use click tracking

### ISSUE THREAD

**Issue by SerbanCiprian** [MisterPhilip/omnibug#232] opened 2023-09-20 10:15 UTC
**Describe the bug**
We want the results of custom dimension 38 to be boolean with "true" and "false" not with number "0" and "1". And if look at the pageview results we have "true" and "false" and not number results. And we want consistency and results to be boolean with true and false.

**Screenshots**
<img width="529" alt="Screenshot 2023-09-20 at 13 09 09" src="https://github.com/MisterPhilip/omnibug/assets/11134908/0ef372e9-8de5-4a42-970b-ec5adf402bb1">
<img width="530" alt="Screenshot 2023-09-20 at 13 09 55" src="https://github.com/MisterPhilip/omnibug/assets/11134908/5358487f-a0bb-40dc-8abc-27491865b61d">

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Chrome
 - Version 117.0.5938.88
 - Omnibug Version 1.21.1

**Comment by MisterPhilip** [comment] 2023-09-26 22:40
Can you provide an example page that this can be replicated on? If you look in the network tab, does it show true/false or 0/1?

**Comment by MisterPhilip** [comment] 2023-10-08 18:51
Closing since no more detail has been provided. 

If this is for Universal Analytics, this is caused by Google's library, not Omnibug. You would need to change your code to send a string version of true/false instead of a boolean. Example below:
![image](https://github.com/MisterPhilip/omnibug/assets/950141/49beacc0-a26c-4796-9112-0231516e4787)

This returns this in the network tab:
![image](https://github.com/MisterPhilip/omnibug/assets/950141/5616200b-cc7b-4b64-be45-636b796cf254)

And thus this in Omnibug:
![image](https://github.com/MisterPhilip/omnibug/assets/950141/0025c45d-eeb9-4ceb-ab92-d073d36bf025)

**Closed by MisterPhilip** 2023-10-08 18:51 UTC
Labels: bug
