### ISSUE TITLE
Omnibug Extension Doesn’t Show in Dev Tools Even When Prop Enabled 

### ISSUE THREAD

**Issue by rjpisc20** [MisterPhilip/omnibug#220] opened 2023-06-29 14:03 UTC
Self explanatory

**Comment by MisterPhilip** [comment] 2023-06-29 14:07
Related to #219?

**Comment by MisterPhilip** [comment] 2023-08-03 23:31
Closing since cannot replicate anything outside of #219, but please reopen with steps to reproduce if you are still having this issue.

**Closed by MisterPhilip** 2023-08-03 23:31 UTC
Labels: bug
